// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_default_block_length
int compute_default_block_length(const Rcpp::NumericMatrix& x);
RcppExport SEXP _tsbs_compute_default_block_length(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_default_block_length(x));
    return rcpp_result_gen;
END_RCPP
}
// blockBootstrap_cpp
Rcpp::List blockBootstrap_cpp(SEXP xSEXP, SEXP n_boot_spec, SEXP block_length_spec, SEXP num_blocks_spec, const int num_boots, const std::string& block_type, SEXP p, const bool overlap);
RcppExport SEXP _tsbs_blockBootstrap_cpp(SEXP xSEXPSEXP, SEXP n_boot_specSEXP, SEXP block_length_specSEXP, SEXP num_blocks_specSEXP, SEXP num_bootsSEXP, SEXP block_typeSEXP, SEXP pSEXP, SEXP overlapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xSEXP(xSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_boot_spec(n_boot_specSEXP);
    Rcpp::traits::input_parameter< SEXP >::type block_length_spec(block_length_specSEXP);
    Rcpp::traits::input_parameter< SEXP >::type num_blocks_spec(num_blocks_specSEXP);
    Rcpp::traits::input_parameter< const int >::type num_boots(num_bootsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type block_type(block_typeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    Rcpp::traits::input_parameter< const bool >::type overlap(overlapSEXP);
    rcpp_result_gen = Rcpp::wrap(blockBootstrap_cpp(xSEXP, n_boot_spec, block_length_spec, num_blocks_spec, num_boots, block_type, p, overlap));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tsbs_compute_default_block_length", (DL_FUNC) &_tsbs_compute_default_block_length, 1},
    {"_tsbs_blockBootstrap_cpp", (DL_FUNC) &_tsbs_blockBootstrap_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_tsbs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
