# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_default_block_length <- function(x) {
    .Call(`_tsbs_compute_default_block_length`, x)
}

blockBootstrap_cpp <- function(xSEXP, n_boot_spec, block_length_spec, num_blocks_spec, num_boots, block_type, p, overlap) {
    .Call(`_tsbs_blockBootstrap_cpp`, xSEXP, n_boot_spec, block_length_spec, num_blocks_spec, num_boots, block_type, p, overlap)
}

